version: '3.8'

services:
  nbp-app8092:
    image: matiuw/nbp-app8092:latest
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: any
    ports:
      - "8092:8092"
    networks:
      - NBP-APP

networks:
  NBP-APP:
    external: true

